package uz.pdp.telegrambotvobkent.entity.enums;

public enum TelegramState {
    START, SHARE_CONTACT, GENERATE_LINK_TO_SUBSCRIBE, SHOW_MENU, SHOW_COMPETITION_MENU, STOP_THE_BOT, STAR_THE_BOT, ENTER_FULL_NAME, CHECK_FULL_NAME,
}
